from typing import Literal

from pydantic import BaseModel, Field


class SupervisorResponse(BaseModel):
    valid: Literal[True, False] = Field(
        description="Valid from the supervisor, if not is need more interactions return True, else return False"
    )
    feedback: str = Field(description="Feedback from the supervisor")


class CodeOutput(BaseModel):
    """Schema for code generation output."""

    code: str = Field(
        description="The generated code, including any imports and explanation"
    )
    imports: str = Field(
        description="Reserved for backwards compatibility, but not used", default=""
    )
    prefix: str = Field(
        description="Reserved for backwards compatibility, but not used", default=""
    )


class SearchResponse(BaseModel):
    """Response of agent that search in the internet"""

    feedback: str = Field(
        description="Fedeback of agent that search the internet for agent of code"
    )
    code: str = Field(description="Code generated by the search")
